### ISSUE TITLE
Riot asks to verify 'this' session when there's no other logged in devices

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12610]

**Comment by jryans** [comment]
Hmm, seems to have slipped through my triage... 😭 @turt2live, have you seen this recently...? I suspect it may have been fixed.

**Comment by turt2live** [comment]
Still getting this:
![image](https://user-images.githubusercontent.com/1190097/80229093-2a43ba80-860d-11ea-9c7e-5c89eef72e9c.png)

Steps to reproduce:
1. Log in to your account
2. Delete all your other devices
3. Sign out (not done in step 2 for safety than anything else)
4. Log back in

**Comment by turt2live** [comment]
I thought I included more details, but the concern here is that it implies that there's another device that can be used. If I knowingly logged out from everywhere it makes it sound like my account has been compromised.

**Comment by jryans** [comment]
Ah okay, so I guess it's the same as https://github.com/vector-im/riot-web/issues/13289?

**Comment by turt2live** [comment]
oh hey, that's where I put the detail. Closing in favour of that.
