### ISSUE TITLE
Electron: Can't enable Desktop Notifications

### ISSUE THREAD

**Issue by carlos22** [vector-im/riot-web#2945]
OS: Ubuntu GNOME 16.04
App Version: 0.9.5 (from https://riot.im/packages/debian)
It is not possible to check "Enable desktop notifications" - just get unchecked when opening the Settings again. Notifications are not working. WM: Gnome3

**Comment by carlos22** [comment]
```
Notifier.js:132 Uncaught TypeError: Cannot read property 'done' of undefined`
```

![stacktrace](https://cloud.githubusercontent.com/assets/526996/21935864/64b18c46-d9af-11e6-897a-07153ebea8b1.png)

**Comment by carlos22** [comment]
In the console:
```
Notification.permission
"granted"
```
I don't know why it fails, any suggestions?

**Comment by carlos22** [comment]
Does not seem to be a system problem as the demo notifications app [1] is working great!

[1] https://github.com/hokein/electron-sample-apps/tree/master/notifications

**Comment by Cenness** [comment]
OS: Windows 10
App Version: 0.9.6 (from https://riot.im/download/desktop/install/win32/x64)
It is not possible to check "Enable desktop notifications" - get unchecked when opening the Settings again. Notifications are not working.
Same error in console.

**Comment by carlos22** [comment]
This is the fix: https://github.com/carlos22/riot-web/commit/6c9d9087e71c578bea5fcd3475b6a73e935b7edc

**Comment by carlos22** [comment]
Fixed in #2994

**Comment by srish** [comment]
This is still not working for me! Nothing happens 
<img width="778" alt="screen shot 2017-01-30 at 1 32 14 pm" src="https://cloud.githubusercontent.com/assets/288353/22442653/f3dce516-e6f0-11e6-8040-10f530867053.png">
on selecting the checkbox "Enable desktop notifications" from Settings or on clicking the "Enable them now" link on the popup.

**Comment by carlos22** [comment]
@srish which version you are using?

**Comment by srish** [comment]
@carlos22 here are the details: 
matrix-react-sdk version: 0.8.6-rc.3
vector-web version: v0.9.7-rc.3
olm version: 2.2.1
