### ISSUE TITLE
pasting image into RTE sent both URL and attachment

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3475]
...and the upload confirmation had no focus

**Comment by lampholder** [comment]
This worked fine for me on chrome and firefox - pasting an image uploaded without displaying the URL, and the confirmation had focus inasmuch as pressing enter confirmed the upload.

Do you have a link to an example of the URL being uploaded (or a room for me to mine to track it down)?

**Comment by lampholder** [comment]
Okay, so Matthew demonstrated IRL that there is something peculiar going on here.

To reproduce:
 - copy an image with alt text from a browser (https://tom.lant.uk/bugs/3475/ if you're feeling lazy)
 - paste it into RTE in chrome

The alt text gets pasted into the text area, stealing the focus from the modal dialogue.

**Comment by t3chguy** [comment]
Tried reproducing, copying an image with/without alt text using right click > Copy Image worked fine - nothing got pasted, upload was prompted. Copying an image by highlighting and then Ctrl+C only ever pasted the Alt text (or nothing if none)

Windows 10
Chrome 58.0.3029.81 (64-bit)
riot.im/develop

**Comment by ara4n** [comment]
i wonder if the new modal dialog focus stuff magically fixed this. will check

**Comment by lampholder** [comment]
When I tried (Mac, Chrome 58, /develop) I found that copying (right click, copy) the image with alt text:
 - uploaded the image
 - dumped the URL into the text area
 - didn't give the modal focus

The same process for images without alt text worked fine (including focusing the modal)

**Comment by lukebarnard1** [comment]
I can't repro on Ubuntu/Chrome so I reckon this is platform-specific to macOS.

**Comment by lukebarnard1** [comment]
Does anyone who experienced this bug have High DPI enabled? Apparently Chrome had a bug that got fixed in Chome 56 at some point - https://bugs.chromium.org/p/chromium/issues/detail?id=667223

**Comment by lampholder** [comment]
My macbook air doesn't have high DPI enabled but is still experiencing the problem on Chrome (59 now)

**Comment by ara4n** [comment]
it does, which makes my life so much better :)

fixed by matrix-org/matrix-react-sdk#1890

**Comment by t3chguy** [comment]
:D
