### ISSUE TITLE
12h timestamp collides with encryption icon

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4046]
### Description

![image](https://cloud.githubusercontent.com/assets/1190097/26510904/a56d6748-421c-11e7-825a-8667446a912f.png)

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment]
where mah mention!?

**Comment by turt2live** [comment]
@t3chguy

**Comment by t3chguy** [comment]
ty

**Comment by ara4n** [comment]
looks like this is fixed now?

**Comment by t3chguy** [comment]
![image](https://cloud.githubusercontent.com/assets/2403652/26512733/d6f4541e-425f-11e7-855e-3daf3f134b6a.png)
still broken for me on /develop/

**Comment by t3chguy** [comment]
@ara4n

**Comment by t3chguy** [comment]
![undefined](https://cloud.githubusercontent.com/assets/2403652/26523028/1ded68e2-4305-11e7-8997-adf8aad5853f.png)
better eg

**Comment by lampholder** [comment]
We shouldn't push this live with the overlap glitch, but we shouldn't block the release on this feature... Hopefully the fix is small enough that it's easy to roll in with whatever else we're doing.

**Comment by turt2live** [comment]
I tried some CSS in Chrome to make this a bit nicer, and can't really decide on a fix. Input appreciated:

1. Pushing the timestamp 8px to the left (colliding with the hover animation)
   ![image](https://cloud.githubusercontent.com/assets/1190097/26588480/b32b285e-4512-11e7-9cda-d5b391416d70.png)
2. Making the sender profile larger by ~10px
   ![image](https://cloud.githubusercontent.com/assets/1190097/26588661/2ad427ca-4513-11e7-95ff-d5a235887024.png)
   The downside being 24hr time looks a bit weird
   ![image](https://cloud.githubusercontent.com/assets/1190097/26588713/5197bd5e-4513-11e7-9d10-f42a14aa8ce3.png)
3. Something I haven't considered

**Comment by uhoreg** [comment]
How about removing the space before the AM/PM?  Or making the font size slightly smaller?

**Comment by turt2live** [comment]
removing the space doesn't save enough space:
![image](https://cloud.githubusercontent.com/assets/1190097/26590373/9a356cec-4517-11e7-95cd-d7333d67d974.png)

Doing both font size and removing the space seems to make it fit (11px -> 10px)
![image](https://cloud.githubusercontent.com/assets/1190097/26590423/c0e8e7e2-4517-11e7-87ca-bdd18eef6bbe.png)

**Comment by turt2live** [comment]
fixed via https://github.com/matrix-org/matrix-react-sdk/issues/969 and https://github.com/vector-im/riot-web/issues/4085

Ended up going with the smaller text and no space solution.
