### ISSUE TITLE
"Jump to first unread message" / Read Marker is really annoying

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4134]
Annoyances:
 - Having an RM for public rooms that I probably don't want to read every message of is annoying because I end up clicking the "X" every time to claim back my screen real-estate. Solutions are 1. and 2.
 - Skim-reading is very frustrating because you have to scroll down, scroll up to catch the RM, scroll down...

I think we should consider the following improvements:
 1. Per-room setting for disabling the RM entirely. This would hide the RM but under the hood set it to the RR.
 1. Disable the RM for public rooms by default. Or provide a global setting to disable/enable it when you first join.
 1. Make it easier to skim-read: update a local RM much more frequently and then debounce the setting of the server-side RM so as not to suffer from rate-limiting instead of tying the server-side rate limiting avoidance strategy to the UI.

**Comment by ara4n** [comment]
Another option would be to just have it skip to the most recent unread message (before your current block) rather than the oldest.

**Comment by turt2live** [comment]
It'd be nice if it was less obtrusive in rooms that aren't being interacted with regularly. For instance, I rarely visit many rooms on my room list. When I do visit those rooms, it's because of a ping (usually) or I'm brought in for another reason. I often don't care too much about the history of the room and end up clearing the read marker just so I can more easily follow along in my short visit to the room before leaving it be for weeks/months/years.

**Comment by ara4n** [comment]
The more I think about this, the more i think the solution is simply to have the 'jump to unread messages' banner take you up to wherever the RM is (if the RM is off the top of the page).  And that's it - it shows you the most recent unread message since you were last in the room.

We might need to increase the delay or metric after which a room is considered read, so if you are just flipping through rapidly it doesn't reset the RM, but I think this is going to be the least unintuitive solution.

We should also give the option to disable it via granular settings as per #7225.

**Comment by ara4n** [comment]
I think the only reason we didn't do this in the first place was because of concern that the RM gets flushed whenever you start reading a room, so you only get one shot to read the room - if you dip into it and decide not to hit the jump to old messages button, you then lose your place.  Perhaps this is better than the current behaviour, though, especially if the prompt hangs around indefinitely until you click on it during a given view of the room (even though the underlying RM has faded away).

The only alternative i can see is the whole enchilada over at https://github.com/vector-im/riot-web/issues/6483.

**Comment by fladd** [comment]
I am constantly confused about the RM. It basically never takes me to where I think it would take me. It most of the time takes me to some point days or weeks ago (basically the last time I clicked the X). When I am in a room, and go away for 5 min, I expect it to take me to the state of when I left the room. Irrespective of whether I have already reset the RM before I left the room or not. Every IRC client out there seems to get this right. But in Riot it seems I always have to manually reset the read marker **even if I don't want go there** every time I switch to a room, in order for it to track the correct new state next time I goo away.

**Comment by natrius** [comment]
Yeh, it seems like its mandatory to click the x after pressing "Get to the last unread message". 

> Skim-reading is very frustrating because you have to scroll down, scroll up to catch the RM, scroll down...

Imho the "Get to last unread message" should also act as "X" and close the message.

**Comment by ara4n** [comment]
> The only alternative i can see is the whole enchilada over at #6483.

Another possibility (which is like a lightweight version of #6483) would be to track the previous RM locations in a list, and let you jump back through them.  This might not be too bad, although unsure what the UX would be to differentiate between "you have unread stuff you really want to jump back to" and "jump back further".

**Comment by ara4n** [comment]
So, turns out that experimenting with the proposed change is pretty much a oneliner; to switch `m.fully_read` at https://github.com/matrix-org/matrix-react-sdk/blob/49ce4ef117b854eff3ab26ae30a1b336a250532d/src/components/structures/TimelinePanel.js#L126 to `m.read`.

The problem turns out to be that users may want to send RRs more rapidly than they clear their RM, however.  So there is perhaps an argument that the client should explicitly update the RM location once the client has decided that the user has read on sufficiently that it no longer wants the old bookmarked location.

**Comment by bwindels** [comment]
> So, turns out that experimenting with the proposed change is pretty much a oneliner; to switch `m.fully_read` at https://github.com/matrix-org/matrix-react-sdk/blob/49ce4ef117b854eff3ab26ae30a1b336a250532d/src/components/structures/TimelinePanel.js#L126 to `m.read`.
> 

Yep, almost, see https://github.com/matrix-org/matrix-react-sdk/commit/65db0fc15522a914686c020820f357cdc9722448

**Comment by nadonomy** [comment]
@ara4n & I just jumped on a call to explore different options for solving this issue, writing up notes here:

[https://docs.google.com/document/d/1PAZYgCfrGJuDOYGTJ8HZH7Pd2LK0yUkW13C9FMwhWHw](https://docs.google.com/document/d/1PAZYgCfrGJuDOYGTJ8HZH7Pd2LK0yUkW13C9FMwhWHw)

**Comment by Tectract** [comment]
How about this: give us an option to COMPLETELY DISABLE these spam notifications, forever.

**Comment by natrius** [comment]
> 
>  COMPLETELY DISABLE these ... notifications

At least per room would be nice. there are some rooms where i don't care whats written before.

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2345.

**Comment by turt2live** [comment]
I disagree - it still shows up when I don't expect it to, just now it's on the far right instead of across the top of the room.

**Comment by nunoperalta** [comment]
In all devices (Android, Web, Desktop, iOS, ...), is it possible that when I open a chat with a number of unread messages, we are auto-scrolled to the first/oldest unread message, instead of defaulting to being scrolled to the bottom?

**Comment by l1ving** [comment]
To add to this, I'm finding it incredibly annoying to see "jump to first unread message" every time someone sends a new message in a DM, despite clicking X on it each time. It'd be nice to be able to disable it entirely.

**Comment by Tectract** [comment]
It's a bug not a feature. The last thing I want is popup notifications about a chat message, in a chat room, that can't be disabled. 

I never asked for anyone to track which messages I have read. It's stalkerish and a major privacy violation too.

**Comment by ggogel** [comment]
This "feature" is entirely broken right now. I'm getting this hint both on web and android in every single chat. And even if I jump to the last message that's supposed to be unread, it doesn't mark them as read. The only way for me to mark messages as read is to click the "X / Mark all as read button" on. Shouldn't simply viewing a message be enough? This marker also doesn't correspond with the new message marker next to the chats. For instance I've chats that don't show a dot, next to them, meaning there no new messages, but when I open them I'm greeted with "jump to first unread message". This is all super annoying and confusing.

**Comment by jivanpal** [comment]
@Tectract, your gripe is about whether you send read receipts at all (and thus whether other people can see which messages you've read), not about the specific feature of telling you which messages you haven't seen, which (I think) could be toggled independently of read receipts. See #2527 for your concern. Also see related discussion in #8959.

**Comment by Tectract** [comment]
My gripe is not about whether other people can see which messages I have read. It's about the entire mechanism of the server tracking which messages I have read and which ones are "new". I don't want that. I actively want that to be turned OFF. It's stalkerish to have a chat room where you track which messages everyone has read and nag them about which ones are "new" or not, it's not a feature anyone ever requested, it's a bug that was implemented by a bad developer who didn't care about user desires or user privacy. 

All I want a chat room to do is STAY on the most recent message and not annoy me with popups or notifications about which messages it thinks I have or haven't read yet. Like the old-fashioned chat rooms used to work. Literally the old AOL chatrooms from 1994 are better than your chat room because they didn't STALK me and NOTIFY me about chat messages all the time in ten ways that can't be disabled.

**Comment by jivanpal** [comment]
@Tectract, perfectly fine that you feel that way, and I agree that it should be an option, but statements such as "it's not a feature anyone ever requested, it's a bug" are simply not true.

**Comment by l1ving** [comment]
To an end user this issue quite literally feels like a bug.. I'm only subscribed here because I found this issue by googling something along the lines of "element not marking messages read properly".

If I'm scrolled down to the bottom, I expect that *I have read all the messages*. Instead I'm shown this silly blue banner saying "jump to first unread message" which is something I had already read when it was sent??. And the banner keeps coming back until I scroll past the message it links to a couple of times.

**Comment by rempelj** [comment]
Just make the banner optional.

**Comment by Tectract** [comment]
**Every notification system should have the option to permanently disable it.** This is a law of good software design. This thread exists because this axiom of good software design has been violated.

**Comment by jivanpal** [comment]
@Tectract, no, this thread exists because the feature does not work properly. There is a difference between wanting the feature to be fixed and wanting to disable the feature.

**Comment by Tectract** [comment]
You can't listen to the users and their desires. You don't care about user privacy. That's what I hear.

**Comment by rempelj** [comment]
This issue is called "Jump to first unread message / Read Marker is really annoying". Which is a subjective opinion, not a bug. The solution is to make the banner optional.

**Comment by Tectract** [comment]
It's a feature request, to make the banner optional, because some of us see the whole banner system itself as a bug, and some of us see it as merely annoying.

**Comment by gwbrown** [comment]
I'll be honest, I don't understand all the points in this thread. But the read marker is still very confusing and makes using Element with public rooms basically non-workable for me. It's very confusing:
1) where it takes me when I click on it, 
2) why it's so slow to do so, 
3) where it took me after I click it, because there's no way to display datestamps on messages, just timestamps, so if I'm going back more than a day I have no idea how many days back I am, 
4) why the scroll bar is all messed up after clicking the RM, and 
5) why there's no option to jump to the oldest unread message instead of the newest when viewing a channel with unread messages.

**Comment by Tectract** [comment]
Personally, I NEVER want which messages I have read to be tracked. I view it as a huge privacy violation. I never want notifications about unread messages in ANY chat room, and I would prefer if people are NOT ALLOWED to tag me, for any reason, ever. I just want to chat. I don't want notifications. No means no.

**Comment by Lamdarer** [comment]
> Personally, I NEVER want which messages I have read to be tracked. I view it as a huge privacy violation.

See: https://github.com/vector-im/element-web/issues/2527
Should be fixed soon

**Comment by Tectract** [comment]
Slowly people are seeing the light. "unread message" means "I am tracking everything you look at.". It's a MAJOR PRIVACY VIOLATION!!!

**Comment by jivanpal** [comment]
@Tectract You don't need to keep repeating the same thing with different amounts of emphasis. We get it.

> I just want to chat. I don't want notifications.

You can toggle ping notifications on a per-room basis.

**Comment by Tectract** [comment]
It's true that it is now possible to turn off ping notifications per room, however this doesn't solve the problem. Slack still tracks which messages I am reading and sends me "unread message" notifications. 

You don't seem to get it. What I want is for Slack to stop tracking which messages I have read, COMPLETELY FOREVER IN ALL ROOMS. What I want is my PRIVACY back.

**Comment by natrius** [comment]
Please, don't get me wrong, but... please stop commenting here. You have absolutely no technical clue how something could work and yet you demand(!) stuff without even asking before. 
Another think: Why should we care about anything that **Slack** does? This Github Repo has nothing to do with Slack.

Still, i try to explain: The unread messages has NOTHING to do with a server. Thats your client doing that and its not tracking anything to be able to do something like that. So you have your privacy back and you can stop commenting here with stuff completely irrelevant for this issue.

**Comment by Tectract** [comment]
Natrius, you are being super-rude. This is not your repo so I don't appreciate your gatekeeping. This thread is about disabling the "unread message" notification, you are going on and on about "ping" notifications, which is a separate issue.

> You have absolutely no technical clue how something could work and yet you demand(!) stuff without even asking before.

Brother I probably got my degree in computer engineering while you were in gradeschool, these types of unwarranted insults don't belong here.

> use_presence = false

Would that stop the server from tracking me? Where do I put that?  It should be a default.

**Comment by jivanpal** [comment]
@Tectract 

> It's true that it is now possible to turn off ping notifications per room, however this doesn't solve the problem.

You mentioned two problems:

1. Element sends read receipts, but you don't want it to.
2. Element gives you notifications, but you don't want it to.

Problem (1) is described by #2527 and now solved in the API, just needs to make its way to the client. Problem (2) is solved in notification settings.

Neither of those problems is the subject of this GitHub issue, so if you have questions or suggestions/requests concerning them (such as your desire for sending read receipts to be disabled by default), please do so in the relevant issue thread or open a new one. This is not the place for it; this issue thread only concerns the UI feature mentioned in the title.
