### ISSUE TITLE
issue to track room change perf regression in 0.12.x

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#4925]

**Comment by krombel** [comment]
fixed by matrix-org/matrix-react-sdk#1354

**Comment by turt2live** [comment]
I'm still seeing ~500ms delays in switching rooms. 

It is significantly better (down from 3-5 seconds), but obviously there's room for improvement :)
