### ISSUE TITLE
Build failure with 0.12.4

### ISSUE THREAD

**Issue by ArchangeGabriel** [vector-im/riot-web#5091]
Trying to package for Arch, with the following steps (from the extracted source tarball):

```
npm install --cache ../npm-cache
npm run build --cache ../npm-cache
```

Results in:
```
npm WARN deprecated babel-preset-es2017@6.24.1: We're super 😸  excited that you're trying to use ES2017 syntax, but instead of making more yearly presets 😭 , Babel now has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user 😎 ! We are also in the process of releasing v7, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and help test it out in beta! Thanks so much for using Babel 🙏, please give us a follow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/development and help support the project at opencollective.com/babel
npm WARN deprecated babel-preset-es2016@6.24.1: We're super 😸  excited that you're trying to use ES2016 syntax, but instead of making more yearly presets 😭 , Babel now has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user 😎 ! We are also in the process of releasing v7, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and help test it out in beta! Thanks so much for using Babel 🙏, please give us a follow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/development and help support the project at opencollective.com/babel
npm WARN deprecated babel-preset-es2015@6.24.1: We're super 😸  excited that you're trying to use ES2015 syntax, but instead of making more yearly presets 😭 , Babel now has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user 😎 ! We are also in the process of releasing v7, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and help test it out in beta! Thanks so much for using Babel 🙏, please give us a follow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/development and help support the project at opencollective.com/babel
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> riot-web@0.12.4 prepublish /build/riot/src/riot-web-0.12.4
> npm run build:compile


> riot-web@0.12.4 build:compile /build/riot/src/riot-web-0.12.4
> npm run reskindex && babel --source-maps -d lib src


> riot-web@0.12.4 reskindex /build/riot/src/riot-web-0.12.4
> reskindex -h src/header

Reskindex: completed
src/VectorConferenceHandler.js -> lib/VectorConferenceHandler.js
src/component-index.js -> lib/component-index.js
src/components/structures/BottomLeftMenu.js -> lib/components/structures/BottomLeftMenu.js
src/components/structures/CompatibilityPage.js -> lib/components/structures/CompatibilityPage.js
src/components/structures/HomePage.js -> lib/components/structures/HomePage.js
src/components/structures/LeftPanel.js -> lib/components/structures/LeftPanel.js
src/components/structures/LoginBox.js -> lib/components/structures/LoginBox.js
src/components/structures/RightPanel.js -> lib/components/structures/RightPanel.js
src/components/structures/RoomDirectory.js -> lib/components/structures/RoomDirectory.js
src/components/structures/RoomSubList.js -> lib/components/structures/RoomSubList.js
src/components/structures/SearchBox.js -> lib/components/structures/SearchBox.js
src/components/structures/ViewSource.js -> lib/components/structures/ViewSource.js
src/components/views/context_menus/GenericTextContextMenu.js -> lib/components/views/context_menus/GenericTextContextMenu.js
src/components/views/context_menus/MessageContextMenu.js -> lib/components/views/context_menus/MessageContextMenu.js
src/components/views/context_menus/RoomTileContextMenu.js -> lib/components/views/context_menus/RoomTileContextMenu.js
src/components/views/dialogs/BugReportDialog.js -> lib/components/views/dialogs/BugReportDialog.js
src/components/views/dialogs/ChangelogDialog.js -> lib/components/views/dialogs/ChangelogDialog.js
src/components/views/dialogs/DevtoolsDialog.js -> lib/components/views/dialogs/DevtoolsDialog.js
src/components/views/dialogs/SetPasswordDialog.js -> lib/components/views/dialogs/SetPasswordDialog.js
src/components/views/directory/NetworkDropdown.js -> lib/components/views/directory/NetworkDropdown.js
src/components/views/elements/ImageView.js -> lib/components/views/elements/ImageView.js
src/components/views/elements/Spinner.js -> lib/components/views/elements/Spinner.js
src/components/views/globals/MatrixToolbar.js -> lib/components/views/globals/MatrixToolbar.js
src/components/views/globals/NewVersionBar.js -> lib/components/views/globals/NewVersionBar.js
src/components/views/globals/PasswordNagBar.js -> lib/components/views/globals/PasswordNagBar.js
src/components/views/globals/UpdateCheckBar.js -> lib/components/views/globals/UpdateCheckBar.js
src/components/views/login/VectorCustomServerDialog.js -> lib/components/views/login/VectorCustomServerDialog.js
src/components/views/login/VectorLoginFooter.js -> lib/components/views/login/VectorLoginFooter.js
src/components/views/login/VectorLoginHeader.js -> lib/components/views/login/VectorLoginHeader.js
src/components/views/messages/DateSeparator.js -> lib/components/views/messages/DateSeparator.js
src/components/views/messages/MessageTimestamp.js -> lib/components/views/messages/MessageTimestamp.js
src/components/views/rooms/DNDRoomTile.js -> lib/components/views/rooms/DNDRoomTile.js
src/components/views/rooms/RoomDropTarget.js -> lib/components/views/rooms/RoomDropTarget.js
src/components/views/rooms/RoomTooltip.js -> lib/components/views/rooms/RoomTooltip.js
src/components/views/rooms/SearchBar.js -> lib/components/views/rooms/SearchBar.js
src/components/views/settings/IntegrationsManager.js -> lib/components/views/settings/IntegrationsManager.js
src/components/views/settings/Notifications.js -> lib/components/views/settings/Notifications.js
src/notifications/ContentRules.js -> lib/notifications/ContentRules.js
src/notifications/NotificationUtils.js -> lib/notifications/NotificationUtils.js
src/notifications/PushRuleVectorState.js -> lib/notifications/PushRuleVectorState.js
src/notifications/StandardActions.js -> lib/notifications/StandardActions.js
src/notifications/VectorPushRulesDefinitions.js -> lib/notifications/VectorPushRulesDefinitions.js
src/notifications/index.js -> lib/notifications/index.js
src/utils/DirectoryUtils.js -> lib/utils/DirectoryUtils.js
src/vector/index.js -> lib/vector/index.js
src/vector/indexedbd-worker.js -> lib/vector/indexedbd-worker.js
src/vector/modernizr.js -> lib/vector/modernizr.js
src/vector/olm-loader.js -> lib/vector/olm-loader.js
src/vector/platform/ElectronPlatform.js -> lib/vector/platform/ElectronPlatform.js
src/vector/platform/VectorBasePlatform.js -> lib/vector/platform/VectorBasePlatform.js
src/vector/platform/WebPlatform.js -> lib/vector/platform/WebPlatform.js
src/vector/platform/index.js -> lib/vector/platform/index.js
src/vector/rageshake.js -> lib/vector/rageshake.js
src/vector/submit-rageshake.js -> lib/vector/submit-rageshake.js
src/vector/url_utils.js -> lib/vector/url_utils.js
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN draft-js-export-html@0.6.0 requires a peer of draft-js@>=0.10.0 but none was installed.
npm WARN draft-js-export-markdown@0.3.0 requires a peer of draft-js@>=0.10.0 but none was installed.
npm WARN draft-js-utils@1.2.0 requires a peer of draft-js@>=0.10.0 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.1.0 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1105 packages in 35.379s

> riot-web@0.12.4 build /build/riot/src/riot-web-0.12.4
> npm run reskindex && npm run build:res && npm run build:bundle


> riot-web@0.12.4 reskindex /build/riot/src/riot-web-0.12.4
> reskindex -h src/header

Reskindex: completed

> riot-web@0.12.4 build:res /build/riot/src/riot-web-0.12.4
> node scripts/copy-res.js


> riot-web@0.12.4 build:bundle /build/riot/src/riot-web-0.12.4
> cross-env NODE_ENV=production webpack -p --progress --bail

 55% 663/880 build modulesError
    at /build/riot/src/riot-web-0.12.4/node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (/build/riot/src/riot-web-0.12.4/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /build/riot/src/riot-web-0.12.4/node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /build/riot/src/riot-web-0.12.4/node_modules/async/lib/async.js:726:13
    at /build/riot/src/riot-web-0.12.4/node_modules/async/lib/async.js:52:16
    at done (/build/riot/src/riot-web-0.12.4/node_modules/async/lib/async.js:241:17)
    at /build/riot/src/riot-web-0.12.4/node_modules/async/lib/async.js:44:16
    at /build/riot/src/riot-web-0.12.4/node_modules/async/lib/async.js:723:17
    at /build/riot/src/riot-web-0.12.4/node_modules/async/lib/async.js:167:37
    at /build/riot/src/riot-web-0.12.4/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/build/riot/src/riot-web-0.12.4/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at /build/riot/src/riot-web-0.12.4/node_modules/enhanced-resolve/lib/Resolver.js:127:10
    at /build/riot/src/riot-web-0.12.4/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/build/riot/src/riot-web-0.12.4/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/build/riot/src/riot-web-0.12.4/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /build/riot/src/riot-web-0.12.4/node_modules/tapable/lib/Tapable.js:134:6
    at Resolver.<anonymous> (/build/riot/src/riot-web-0.12.4/node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:24:12)
    at Storage.finished (/build/riot/src/riot-web-0.12.4/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at ReadFileContext.callback (/build/riot/src/riot-web-0.12.4/node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:421:13)
resolve file
  /build/riot/src/riot-web-0.12.4/node_modules/matrix-react-sdk/lib/wrappers/withMatrixClient doesn't exist
  /build/riot/src/riot-web-0.12.4/node_modules/matrix-react-sdk/lib/wrappers/withMatrixClient.webpack.js doesn't exist
  /build/riot/src/riot-web-0.12.4/node_modules/matrix-react-sdk/lib/wrappers/withMatrixClient.js doesn't exist
  /build/riot/src/riot-web-0.12.4/node_modules/matrix-react-sdk/lib/wrappers/withMatrixClient.web.js doesn't exist
  /build/riot/src/riot-web-0.12.4/node_modules/matrix-react-sdk/lib/wrappers/withMatrixClient.json doesn't exist
resolve directory
  /build/riot/src/riot-web-0.12.4/node_modules/matrix-react-sdk/lib/wrappers/withMatrixClient doesn't exist (directory default file)
  /build/riot/src/riot-web-0.12.4/node_modules/matrix-react-sdk/lib/wrappers/withMatrixClient/package.json doesn't exist (directory description file)
 70% 1756/1756 build modulesnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! riot-web@0.12.4 build:bundle: `cross-env NODE_ENV=production webpack -p --progress --bail`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the riot-web@0.12.4 build:bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/riot/src/npm-cache/_logs/2017-09-20T14_28_38_702Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! riot-web@0.12.4 build: `npm run reskindex && npm run build:res && npm run build:bundle`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the riot-web@0.12.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/riot/src/npm-cache/_logs/2017-09-20T14_28_38_740Z-debug.log
```

Content of the aforementioned log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--cache',
1 verbose cli   '/build/riot/src/npm-cache' ]
2 info using npm@5.3.0
3 info using node@v8.5.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle riot-web@0.12.4~prebuild: riot-web@0.12.4
6 info lifecycle riot-web@0.12.4~build: riot-web@0.12.4
7 verbose lifecycle riot-web@0.12.4~build: unsafe-perm in lifecycle true
8 verbose lifecycle riot-web@0.12.4~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/build/riot/src/riot-web-0.12.4/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle riot-web@0.12.4~build: CWD: /build/riot/src/riot-web-0.12.4
10 silly lifecycle riot-web@0.12.4~build: Args: [ '-c',
10 silly lifecycle   'npm run reskindex && npm run build:res && npm run build:bundle' ]
11 silly lifecycle riot-web@0.12.4~build: Returned: code: 1  signal: null
12 info lifecycle riot-web@0.12.4~build: Failed to exec build script
13 verbose stack Error: riot-web@0.12.4 build: `npm run reskindex && npm run build:res && npm run build:bundle`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid riot-web@0.12.4
15 verbose cwd /build/riot/src/riot-web-0.12.4
16 verbose Linux 4.12.13-1-ARCH
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build" "--cache" "/build/riot/src/npm-cache"
18 verbose node v8.5.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error riot-web@0.12.4 build: `npm run reskindex && npm run build:res && npm run build:bundle`
22 error Exit status 1
23 error Failed at the riot-web@0.12.4 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by turt2live** [comment]
I'm also seeing this. Strangely, only on builds that didn't build the RC previously.

**Comment by BennZoid** [comment]
I am also seeing this exact problem while attempting to update the build for Solus.  Both the same error message and the same information in the logs.

**Comment by dbkr** [comment]
Looks like this was a build issue with v0.12.4 - I've just released v0.12.5 with the fix. Sorry!

**Comment by TheLastProject** [comment]
@ArchangeGabriel Please confirm 0.12.5 fixes it for you as I still have a build issue with 0.12.5.

**Comment by silkeh** [comment]
I filed #5098 for the build issue with 0.12.5.
