### ISSUE TITLE
Topics (and possibly other fields) spontaneously reset in RoomSettings whilst you are editing them

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6019]
### Description

I've seen this happen in the user settings as well (uploading an avatar, and while it's uploading changing your display name).

Here's a gif:
![overwrite_topic](https://user-images.githubusercontent.com/1190097/35235396-3e73eb90-ff61-11e7-90b1-d06901d3a354.gif)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
This is also affecting the room alias entry in the room settings. It's more than annoying.

**Comment by lukebarnard1** [comment]
When the avatar changes, and the new avatar event comes down the /sync stream, a `forceUpdate` happens and the input is reset based on the current topic as determined by the js-sdk.

Options:
 1. Persist the room topic as soon as the text field loses focus. We'd have to move all other inputs over to updating the server state as soon as interaction has finished (i.e. we remove the "Save" button).
 2. Only upload the new avatar and change the avatar of the room when we hit "Save". This is actually already embodied in a discussion that we've already had: "Save" vs. updating immediately. 

We've already decided to go for the "update immediately" option for settings in general. This would solve this issue (i.e. we chose option one above).

**Comment by turt2live** [comment]
@lukebarnard1 something else must be going on then. With an updated /develop I'm still having troubles typing out aliases. Almost as if the room settings are taking a while to load their parts and setting state async to each other.

**Comment by lukebarnard1** [comment]
@turt2live would you be able to give a screen recording so we can see what's going on? Or if you could describe exactly what you're seeing step-by-step, that'd be great.

**Comment by turt2live** [comment]
Easily reproduced with this:

1. Create a new room
2. Invite several bots to the room in one action (in my case: `@voyager:t2bot.io`, `@echo:t2bot.io`, `@haiku:t2bot.io`, `@email:t2bot.io`, and `@hyperbot:t2bot.io`)
3. Before the bots join, open the room settings and start typing a new alias - as the bots join the alias will be reset.

**Comment by turt2live** [comment]
I suppose it's possible that https://github.com/matrix-org/matrix-react-sdk/pull/1746 fixes the issue. I thought it was merged already because the issue was closed :/

**Comment by lukebarnard1** [comment]
>I suppose it's possible that matrix-org/matrix-react-sdk#1746 fixes the issue. I thought it was merged already because the issue was closed :/

Oh, well the PR shouldn't have an effect on alias editing - I only pushed fixes for name and topic editing.

**Comment by ara4n** [comment]
this is certainly still broken. are you saying the topic resets every time *any* state event comes down /sync?

**Comment by ara4n** [comment]
@lampholder this means that i can't edit topics or other roomsettings basically, and is a regression - i'm tempted to suggest getting it into 0.14? :/

**Comment by ara4n** [comment]
(adding it given the dup i filed was on 0.14)

**Comment by lukebarnard1** [comment]
@ara4n travis' issue is now only with setting aliases. The PR that was merged should fix the issue for room names and topics.

**Comment by ara4n** [comment]
This is still broken despite the PRs and is incredibly frustrating. I don't think it has anything to do with echos of room state coming back down /sync, but possibly some kind of React lifecycle screwup where something is remounting the component?

To reproduce, just try to edit the topic and see the field suddenly delete itself from under you whilst you're typing.

**Comment by lukebarnard1** [comment]
Looking into this, I've only been able to reproduce this mid-topic-edit when the client receives:
 - a change in the room's avatar or name
 - a membership change to that room

It doesn't happen when the client receives:
 - unhandled room state
 - messages (including messages)

**Comment by t3chguy** [comment]
Okay, after a `shouldComponentUpdate` on the roomId it seems to work
but then again I struggled to reproduce it reliably so it could just be chance.

**Comment by t3chguy** [comment]
Would be great if others who were hit by this more consistently could test the PR

**Comment by turt2live** [comment]
The gif in the OP should be a 100% reproducible case.

**Comment by t3chguy** [comment]
> (and possibly other fields)

Yup, most fields, alias inputs etc

**Comment by lukebarnard1** [comment]
I think I'll have another crack at this, given how much grief it causes.
