### ISSUE TITLE
[Feature Request] Disabling auto update in Windows Desktop

### ISSUE THREAD

**Issue by szimszon** [vector-im/riot-web#8234]
I would like to have some means to keep an old version of Riot without being auto updated.

I'm a bit frustrated because of the issue in #8229 most of my colleagues ~15 people lost access to our Matrix server - possibly lost their e2e keys and had hard time to switch back to prev. version. And this happened after I told them not to upgrade riot and after restart/reboot/another workday they just realized that Riot had updated itself on Windows10 and can't connect to any server anymore.

:-(

**Comment by turt2live** [comment]
Fixed by https://github.com/vector-im/riot-web/pull/8911 - provide `--no-update` to the executable and it shouldn't update.

**Comment by tom709** [comment]
I am running the latest version of Element (currently 1.7.20) on Windows 10 with the command line "...\AppData\Local\element-desktop\Element.exe --no-update" (target of start menu entry in the Startup folder; without quotes) and it regularly installs updates. Is the feature broken?

**Comment by vertigo220** [comment]
This is absolutely still not working. Added that command to the shortcut (which, by the way, is the laziest, most idiotic possible "fix" for this ridiculous, data-wasting issue) and it's still auto-updated _multiple times_. It's not even worth opening a new issue; this dev team clearly doesn't care about issues that affect the users. I'm over this garbage software, and it's no wonder Matrix is having such a hard time gaining traction when _this_ is the flagship app for it.
