### ISSUE TITLE
Option to ignore that a user has unverified devices

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8802]
It's very unlikely that I'll ever verify someone's devices when they live on another continent. It'd be great to have an option to get rid of all the warning icons littering my screen on a per-user (or possibly app-wide) basis. 

As an extra level of granularity: give me the option to also suppress the unknown devices error when sending a message.

These options should not prevent me from verifying a user's devices if I ever happen to be in the same room with them and want to actually verify their devices.

**Comment by markusschweitzer** [comment]
any news on this?

**Comment by uhoreg** [comment]
Is this sufficiently fixed with the cross-signing work?

**Comment by jordannewport** [comment]
The real issue here is that if I cannot verify even one device of everyone in a room (e.g. different continents, or in an encrypted room with dozens-hundreds of users), then I still get warned when they send messages, and when I send a message I still get nagged that there are unverified devices present.

Cross-signing helps with a lot of verification issues, but I don't think it helps with this one.

**Comment by uhoreg** [comment]
The cross-signing work involved dropping the nag message in some common situations.  I haven't tried it myself, but I think @turt2live has, and he opened this issue, so I'm going to let him decide if he considers this sufficiently fixed.

**Comment by turt2live** [comment]
oh, yes, this is fixed.
