### ISSUE TITLE
missing translation message

### ISSUE THREAD

**Issue by worldowner** [vector-im/riot-web#8879]
### Description

So far I was using Riot 0.17 (and older versions) and I've never seen "missing translation". After I installed 1.0.1 most of strings are preceded with "missing translation" message. I tried to reload Riot and clear cache and reload but the messages are still there. I also tried changing the language but problem persists.

I use Firefox 65.0.1 on Linux, Riot instance I use is self-hosted (on nginx).

- **Platform**: web

For the web app:

- **Browser**: Firefox 65.0.1
- **OS**: Linux
- **URL**: self-hosted Riot 1.0.1

**Comment by jryans** [comment]
Thanks for the report. We've seen this as well. It should be fixed for future releases by https://github.com/vector-im/riot-web/pull/8710. If you see it again in the next release, please let us know!

**Comment by jryans** [comment]
Oh, I read too fast and missed that you are still seeing. The issue should be that the language files are being cached by the browser for too long. Is it fixed by a "hard refresh" in the browser (usually Cmd-Shift-R or similar)?

**Comment by worldowner** [comment]
Unfortunately Ctrl-F5 and Ctrl-Shift-R don'tt help. I still see missing translation messages.

**Comment by jryans** [comment]
Can you check which URLs aren't loading using the browser's DevTools?

**Comment by worldowner** [comment]
I receive 404 for home.html (which I don't have) from Riot\s vhost and _matrix/client/r0/room_keys/version from Synapse's vhost. Other requests are served with 200 or 206.

**Comment by jryans** [comment]
What about things like `languages.json`, `en_EN.json`, etc.? These are the Riot files related to strings.

Do those requests succeed? If so, were they updated as part of updating Riot?

**Comment by worldowner** [comment]
The are 200 but the Date header has an old value. So cached.
I'm sure that everything was updated. I untar new version, copy config file and then change symlink so that it points to new version.

**Comment by jryans** [comment]
If you search one of the bad strings from the UI in the `en_EN.json` file, is it there?

**Comment by worldowner** [comment]
Yes. Checked with "General" and "Preferences".

**Comment by jryans** [comment]
Is this still an issue for you? So far, it sounds like you may need to tweak the cache settings of what web server you use to serve Riot so that the browser receives the latest copy. (https://github.com/vector-im/riot-web/pull/8710 should "solve" this in the next release since each version of these files will use a unique URL.)

**Comment by worldowner** [comment]
No, currently it is fine. I'm not using any fancy caching on web server. It's very basic configuration.There's not much to change here:

server {
  listen 443 ssl http2;
  server_name riot.mydomain;

  access_log /var/log/nginx/ssl_riot.mydomain-access.log combined;
  error_log /var/log/nginx/ssl_riot.mydomain-error.log error;

  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

  ssl_stapling on;
  ssl_stapling_verify on;
  ssl_trusted_certificate /etc/letsencrypt/live/mydomain/fullchain.pem;
  ssl_certificate /etc/letsencrypt/live/mydomain/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/mydomain/privkey.pem;
  ssl_dhparam /etc/letsencrypt/live/dhparam.pem;

  ssl_session_timeout 1d;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:50m;

  root /opt/riot;
  index index.html;
}

**Comment by jryans** [comment]
Hmm. At this point, I am unsure what to suggest. So far, I don't see any evidence that there is a bug in Riot. You have confirmed that the translation files on disk contain the new strings. However, somehow the browser is receiving an old copy when Riot requests it.

Could you double-check that the URL for `en_EN.json` that Riot is requesting actually maps to the new file where you found the correct strings? (I'm running out of ideas on how this could go wrong...)

Maybe try unpacking Riot to a fresh directory (assuming you usually unpack new versions on top of old ones) and see if that changes anything?

**Comment by worldowner** [comment]
I'm sure that files are mapping correctly. For now let's close this issue. I'll try your suggestions about fresh directory if problem happens again.

**Comment by NonstickAtom785** [comment]
I'm getting a bug that states this on Chrome OS. It only shows up a few times and I have to close app and reopen it. Not I'm using the web application and not the Android App.

Here's a screenshot:
![image](https://user-images.githubusercontent.com/36454623/75707886-5b46e500-5c85-11ea-9f99-f20e0ad3fc90.png)
