### ISSUE TITLE
People are losing camera/microphone permissions in the desktop app

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8993]
As far as I can tell, Electron shouldn't be losing permissions to this sort of thing. There's also no avenue I can find that allows for the app to re-request permissions.

For a bit of history: 
* A few days ago I helped someone in #riot-web work out why their Windows version of Riot wasn't letting them make calls (lack of media permissions). They ended up fixing it in the Chrome browser and it magically worked after some fiddling with the desktop app - unsure of the complete steps taken to fix it.
* Another user ( https://github.com/vector-im/riot-web/issues/8979#issuecomment-468252344 ) was having a similar issue on kbuntu and did a similar "fix it in the browser and make the desktop app work" series of steps.

Reporting as this is becoming a trend.

**Comment by dbkr** [comment]
Just tested and my call failed because electron didn't have perms. I have absolutely no idea how fiddling with chrome would fix anything - this sounds like they may be confused.

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/852

**Comment by rbraley** [comment]
I still have this bug in v1.1.1 on mac desktop. Is this fix included in that release?

**Comment by jryans** [comment]
> I still have this bug in v1.1.1 on mac desktop. Is this fix included in that release?

Yes, it was first released with 1.0.5. I would suggest opening a new issue so we investigate why it's not working for you.

**Comment by rubo77** [comment]
I have this problem, since I installed the desktop app on (snap image in Ubuntu 19.10)

I guess it is a snap problem in gnome?
